# Generated by Django 5.2.13 on 2026-04-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('raw_request', models.TextField()),
                ('intent', models.CharField(choices=[('send_money', 'Send Money'), ('get_airport_transfer', 'Get Airport Transfer'), ('hire_service', 'Hire Service'), ('verify_document', 'Verify Document'), ('check_status', 'Check Status')], max_length=50)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('risk_reason', models.TextField(blank=True)),
                ('employee_assignment', models.CharField(choices=[('finance', 'Finance Team'), ('operations', 'Operations Team'), ('legal', 'Legal Team'), ('customer_support', 'Customer Support')], default='customer_support', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.task')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('task', 'step_number')},
            },
        ),
    ]
